public class ProblemRNA
{
    public static void main() {
        final String inputDNA = "GTCGTATAGGATAGTGCAGTCAGCAATTCTCCTCGGTCGTTAGCAATTGTTGACCCGTTCGCACAGCCACGGGTACGCCTCAGTCACTGTTGTGGGCGATCCACGAAGTTTAACCAAAATCACATCAAGGGCTGGCCGTGTATAAGTACCGACACCAGGCCGTAGTAGATGCTGTCCTCTAATCGTTCCCACAGCTAATTTGAGCCCCCGGCTTCGTCCAGTCTCCCCAATGGTTCCATACAATTGAAGATGTAGAACATGGAGTTATCGTTACAGGGCACCGGTGCGTCTTTAGTCCCAGGCAATCTGGACGTATCGCTAGTCGTTGACAACTTCGTTAAATTCTGAGCGGAGCGACACCTGTCCTCAGGAAAAAAGCGATAACTGAGTCCTCCCGGACGGACAATACTCCACGTACACTATAATAGGCATCGGTGGACCTCTTCGCTCCTACAATACTGGCCGGCCCTAACTTGGGACGCTTCGTATTCACACTACGCAACGACAATGTTACAGCTACTACAACAGCGTAGTCCGGTACGCAACGGCTAGAGGATTTGAGTGGGGACGTCAAGATAATCGTATATTTCTCGCATAGAACACACACTGTCCCACATTCTGAACTGATATCGAACGGGGGCCGCCGGGCTTGGCTGTTACCTTCCAGGCGAAATGCCCTAGCAGCACTATAGGTAGGTTCGATATTCACCCGCTTCGTCGCGGTTGGAGCTGTCGAGTGATGATTTAACATGTCCTCTTGACTCGAAGAGGCGGTGACTCTGGATAAAAGCATACAACTACGGAGAACCGTTATCAACTTGTGGACAAATACATGGAGAGTAAAGCTGGAGTTACGTATATCACTCATCTGTGCGTAGTGCGAAAGATCACTGGTGTGGCTTAACCACAGATGAATAAGGAATGTA";
        final String output = transcribeDNAtoRNA(inputDNA);
        System.out.println(output);
    }
        
    private static String transcribeDNAtoRNA(String dnaString) {
        StringBuilder rnaStrand = new StringBuilder();
        
        for (char nucleotide : dnaString.toCharArray()) {
        if (nucleotide == 'T') {
        rnaStrand.append('U');
        } else {
            rnaStrand.append(nucleotide);
        }
}
        return rnaStrand.toString();
    }
}
    
