public class ProblemREVC {
    public static void main() {
        final String inputDNA = "GAAGCCTATCGGACGGTCCATCTTTATGTGTGTCGGCCGTCCCATGCGTAAGTTATTGACTTCGACGGATTACATACTAGACCTGATACAGCAGTGCGACCCAATATCCGTGGATTTGACATGGGGAATCTGGTAACTGTAGCTAACAGTGAGACCGAGCCCTGAGGCTGGACGTGCTGCCGACATCCAGGCCATATAGAGGGTTTAGTCAGGTCGCCGATTGTTTCGAGTGCGCAACCGTTGTTTCGATGGCAGGCAACGCTTGTTCTGGAGGAAATTAGATCCGTGTCGAATGCCACGAGGTGCTATGTGTGTTTCGGTGTCCTCCGCGTTAGTATATATCCCATCCTTTAGAATTGTGGTAATCTCACCACGTAGGCAGCTGGGCGGAGACCTAGCCCTGGGCGAGTTCATGATACGAGCTTGCTTTCAGAATTCGTAAGCTGAGCCAGCTTAGGCCGCTCTAACCAACACCGGTACGGCTTTCGCCTACAACAGCAGTAACACGTGACGCCCGTGCAATGTCGAATGCGCTACGTGCTGTAGGATAAAAAGCGCTAGGATTCGAATGGGTCTGGAGGCATTCGGCCAGGCCATTACAAATGTCCACAGCTCGAATGGCTGTTGGGGGCATTCTGGAATCCGCGTCCAGGCCCGCGTAGAATACGAACCGCTAGTATCTGATGCGGTACTGTCAGGGCGTTTTGAGGCACAGAATAGGAGCACGTGTCGAGGCCTTCTACTATTCACATAGTGACCGGAGGCTATTTTTCAAATGCCCCACGGCGCGCATACAGTCAAGATAGGCAGAACCCTACGTCTGAGGGGCCTCTAGAAAGCGCTGACCAAAAACGCAGATATTATAGGTTTCTGATCCTGAAGTTCCTCCGTAGAACTCTCTAGGGATACGCAGTTTGCTCCATGGAGTCTTCGTTATTGTGACATAGTGGCAGGACCATTTTACC";
        final String output = reverseComplement(inputDNA);
        System.out.println(output);
    }
        
    private static String reverseComplement(String dnaString) {
        StringBuilder result = new StringBuilder();
        
        for (char base : dnaString.toCharArray()){
            if (base == 'A'){
                result.append ('T');
            } else if (base == 'T'){
                result.append ('A');
            } else if (base == 'C'){
                result.append ('G');
            } else if (base == 'G'){
                result.append ('C');
            }
        }
        return result.reverse (). toString();
    }    
}

