public class ProblemHAMM {
    public static void main() {
        final String inputDNA1 = "CCTGTACTGAGGGTAAAGCCTACATACGTGGAGCTCGATCTTTGTTTGGGATCGGCAACGATGATCTTTAAACTAATCATCCTTTTATTGATAAATGTTTGGATAAACATCCCATTGGGTGTCGTCGACCCCATCTATACTACATATGACTTTTCGAGGGCAATGGTAGATTCGCACCTTCGGCATCCCATGAATACTGCGAAAGGTAAAGGAGTATGAGTATTTAGTGCGGGTGGGTGTCCACAATCCCTCAGCCCAGCAGGAGTGTGCGGCAAAGGGTATCTGGTTTCTGGCCCTCCCAAAAAGATCACTTTTTCGCTTCAGCAATAGGCGATGTGGGGTCATAGTTGTTGTTACTCGGTGACTAATTTTCCGACCTGGTTACCAGGTGCGCAAGTCCTCAGTGATACTGGTCTTGGCGAGTATTCAGCATGGTGTCACGAGCTAAACAACCCATCTCCGTCAAAGTGCTACAAGCCTTCCGCATGATGAAGGAAGTCAGAAATGCTTCCTGTCCCGCAGGCTGGAACATTAAAGTGGAGCATTTTGGAGACCTTTATCCTTTTATTGACGAGGACAGACTCCCTGTCGTAGAAATTTACGGCCAGGTGTAAAGAGGCAGGCCGGCCGCAGAACACCGTACCAAATTGCTCACCTGTCCTCACATACCTATACGCGATAGACCATTGTTTTCCTTTAAGGGTTCCGGTAGTGAGCATTTGCTGACATGACCGGCCAGGGCAAATGCAGAGAATCCACCTGGGTAAAAGACTAGTCGACACACCCAAGATAACCTGGTCACCAATTCGATTCCGTCGGGAAGCAAGATATGATACAGGCTCCCATACATGAAGCAGCGTCACCGAATACCAACGTCACCTCTAGCAACTCCATAGAGAC";
        final String inputDNA2 = "CCTGTGCTGCGCACGGTACTGATCCACGTGGAGGTCGATTTCTAGCTGCAGGGGGCAGGCCAGATCGTGTAGAAGATAGAACGTTTAGTTACAATCGGTGGGAGGGGCAATCACTGAGGGGTAGGGATGCTAAAATTGGTGACAGATGACCTATAACAGTCAATGTACAGTTGGCACCGACGGGACCCGAACACTCCTTCTTCCGCCAAGAGAGTATGACATTATATGCCGACATAATGATCGCCATGCATTAGCACAACTGTTAGTACCCGCTCAGGGTTACCAATTTAGGGCCCTACTTAAGAGTTCACCTATAAACAGCCGAAGTCAGACAGTGCAAGCTTGAGTTGCTAGTACCGGGGTAATAATAGGCCGGGGAAGGTACCATGCGCTTACCTCGTGTGTGATATTTATCGCAGCAATCACGTAGGATGCTGTCGCGAATTCGAGACCTCGTTACAGACACAAGGGCTCTAGCCGTAGACGGGTCCCAAGCAGTGATAAATGCTCACTGCCGGGAGCATTGTTGGATTACAAGTAAAAAATTACATGACGTTTATCATGTCACGGACGAAATGTGCCTTATTGCGGTAGAATTCTTCCGCAAGAGACAAATTGCCAGCGTGCCAATTGTTCATAGCGTCAAGCACACCGCCGCGCCGAAACCGCCAATCAGAAAACCGCAGTTTGTTGCTCTCCAGGATTGCGGATGGGTGTATAACCGGTTGTGAGAGGCGCACCCAGATCCACGTAACGCCGCCTCATAAGGATCTAGTCGACATATCCAAATCAACCAGCTTATCAGCTTTATCGAGTCGGCACGTGAGCGCTGTTAGTGGATCGGATTCATTATGGGGCTTCGTACAAAGGTTTTCTAACCCCGAAATTCTATCTAGATCG";
        final int output = hammingDistance(inputDNA1, inputDNA2);
        System.out.println(output);
    }
        
    // This should take the given strings and return the number
    //   of times they differ at the same location
    private static int hammingDistance(String a, String b) {
        int count = 0;
        
        for (int i = 0; i <a.length(); i++){
            if (a.charAt(i) != b.charAt(i)){
                count++;
            }
        }
        return count;
    }    
}

